#!/bin/bash

# Configuration file

#----------------------------------------------------------------------------
# Set folder paths - DO NOT CHANGE THESE VARIABLE NAMES. The folder names are case-sensitive and brainageR expects these specific variables.

# username			user or group name
# brainageR_dir		path to top-level brainage folder - do not change folder name
# SCRIPTS_DIR		path to scripts
# FSLDIR			path to FSL version
# matlab_path		path to MATLAB version
# spm_dir			path to SPM12
#----------------------------------------------------------------------------
username=your_username # CHANGE THIS

brainageR_dir=/scratch/$username/brainageR
FSLDIR=/software/fsl/6.0.5.1
matlab_path=/software/matlab/r2022a
spm_dir=/software/spm/12

#----------------------------------------------------------------------------
# Set project parameters

# study				change STUDY_NAME to study/project_name
# ses				BIDS session (i.e., timepoint) 0x, where x is some number (e.g., for baseline/T1: ses=01; T2: ses=02). If you only have one timepoint, then keep as-is.
#----------------------------------------------------------------------------
study=study_name # CHANGE THIS
ses=01
#----------------------------------------------------------------------------
# I/O folders

# SCRIPTS_DIR       Path to the brainageR scripts directory
# BIDS_DIR			Path to the BIDS directory
# DICOM_DIR	        Path to the DICOM directory
# LOG_DIR	        Path to the log directory
# T1_DIR			Path to the directory containing raw T1w
# OUT_DIR			Path to brain age output
# CONFIG_BIDS       Path to dcm2bids config file
#----------------------------------------------------------------------------
SCRIPTS_DIR=$brainageR_dir/software
DCM_BIDS_DIR=$brainageR_dir/dcm2bids
LOG_DIR=$SCRIPTS_DIR/logs
T1_DIR=$SCRIPTS_DIR/brainageR_t1
OUT_DIR=$SCRIPTS_DIR/brainageR_output/$study

BIDS_DIR=/path/to/bids # CHANGE THIS OR COMMENT OUT
DICOM_DIR=/path/to/dicoms # CHANGE THIS OR COMMENT OUT
CONFIG_BIDS=$SCRIPTS_DIR/bids_config/config.json
