# .bashrc

# Clear environment of any current modules
module unload all

# Need to load FSL and run the set-up alias before loading anaconda, otherwise there will be a module conflict
module load fsl/6.0.5.1
fsl-setup

module load matlab/r2022a
module load r/4.2.1/b1
module load spm/12
module load anaconda/5.3.0

# Set path for compiler version that is compatible with the software, otherwise an older version is used by default
export LD_LIBRARY_PATH="/software/gcc/9.1.0/lib64/libstdc++.so.6.0.26:$LD_LIBRARY_PATH"

# Source conda and activate environment
source /software/anaconda/5.3.0/etc/profile.d/conda.sh
conda activate brainager
